#!/usr/bin/env bash
# Print FarmOS — one-command server install.
# Usage:
#   ./install.sh
#   ./install.sh --host http://192.168.1.50:3000
set -euo pipefail

cd "$(dirname "$0")"

HOST_URL=""
HOST_SET=0
RESET=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --host)
      HOST_URL="${2:-}"
      HOST_SET=1
      shift 2
      ;;
    --reset)
      RESET=1
      shift
      ;;
    -h|--help)
      cat <<'EOF'
Print FarmOS installer

Usage:
  ./install.sh
  ./install.sh --host http://192.168.1.50:3000
  ./install.sh --reset

This script installs Docker if needed, writes a .env file, and starts the app
(API, UI, scheduler worker, and the PrusaSlicer slicer-worker).
Open the printed URL and complete the first-run wizard.

--reset  Stop containers and delete Postgres/Redis volumes so the setup wizard
         runs again. Shop data is wiped. The .env file is kept.
EOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Try ./install.sh --help" >&2
      exit 1
      ;;
  esac
done

if [[ ! -f docker-compose.yml ]]; then
  echo "Run this from the Print FarmOS folder (docker-compose.yml is missing)." >&2
  exit 1
fi

say() { printf '\n==> %s\n' "$*"; }

detect_ip() {
  local ip=""
  ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit }}' || true)"
  if [[ -z "$ip" ]]; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  if [[ -z "$ip" ]]; then
    ip="$(ip -4 addr show scope global 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1 | head -n1 || true)"
  fi
  echo "${ip:-127.0.0.1}"
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n'
    return
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets; print(secrets.token_urlsafe(48))"
    return
  fi
  head -c 48 /dev/urandom | base64 | tr -d '\n'
}

DOCKER=()
compose() { "${DOCKER[@]}" compose "$@"; }

ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    DOCKER=(docker)
    return
  fi
  if command -v docker >/dev/null 2>&1 && sudo -n docker info >/dev/null 2>&1 && sudo -n docker compose version >/dev/null 2>&1; then
    DOCKER=(sudo docker)
    return
  fi
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    echo "Docker is installed but this user cannot talk to the daemon yet."
    echo "Trying with sudo..."
    if sudo docker info >/dev/null 2>&1; then
      DOCKER=(sudo docker)
      return
    fi
  fi

  say "Installing Docker"
  if [[ "$(id -u)" -eq 0 ]]; then
    curl -fsSL https://get.docker.com | sh
  else
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker "$USER" || true
  fi

  if docker info >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    DOCKER=(docker)
    return
  fi
  if sudo docker info >/dev/null 2>&1 && sudo docker compose version >/dev/null 2>&1; then
    DOCKER=(sudo docker)
    echo "Docker is ready via sudo. Log out and back in later to use docker without sudo."
    return
  fi

  echo "Could not install or reach Docker. Install Docker Desktop / Docker Engine, then re-run ./install.sh" >&2
  exit 1
}

write_env() {
  local url="$1"
  local secret dbpass
  secret="$(random_secret)"
  dbpass="$(random_secret | tr -d '/+=' | cut -c1-24)"
  cat > .env <<EOF
# Generated by install.sh — edit if you add WooCommerce, Shopify, or notifications.

SECRET_KEY=${secret}
POSTGRES_PASSWORD=${dbpass}
DATABASE_URL=postgresql+asyncpg://farmos:${dbpass}@db:5432/farmos
REDIS_URL=redis://redis:6379/0

CORS_ORIGINS=${url}
PUBLIC_APP_URL=${url}
SIMULATED_TIME_SCALE=1

WOOCOMMERCE_URL=
WOOCOMMERCE_KEY=
WOOCOMMERCE_SECRET=

SHOPIFY_SHOP=
SHOPIFY_ACCESS_TOKEN=
SHOPIFY_WEBHOOK_SECRET=
SHOPIFY_API_VERSION=2024-10

NTFY_SERVER=https://ntfy.sh
NTFY_TOPIC=
NTFY_TOKEN=

PUSHOVER_APP_TOKEN=
PUSHOVER_USER_KEY=
DISCORD_WEBHOOK_URL=
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
NOTIFY_WEBHOOK_URL=

SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=farmos@localhost
SMTP_TO=

# Production slicer (PrusaSlicer CLI runs in slicer-worker, not in the API).
SLICER_BIN=prusa-slicer
STL_MAX_BYTES=83886080
SLICER_CPUS=2.0
SLICER_MEMORY=2g

TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM=
SMS_TO=

UPLOAD_DIR=/data
RUN_SCHEDULER=false
APP_VERSION=dev
EOF
}

set_host_in_env() {
  local url="$1"
  if command -v python3 >/dev/null 2>&1; then
    PUBLIC_APP_URL="$url" python3 - <<'PY'
from pathlib import Path
import os, re
p = Path(".env")
text = p.read_text()
url = os.environ["PUBLIC_APP_URL"]
for key in ("PUBLIC_APP_URL", "CORS_ORIGINS"):
    if re.search(rf"^{key}=", text, re.M):
        text = re.sub(rf"^{key}=.*$", f"{key}={url}", text, count=1, flags=re.M)
    else:
        text += f"\n{key}={url}\n"
p.write_text(text)
PY
    return
  fi
  local tmp
  tmp="$(mktemp)"
  awk -v url="$url" '
    BEGIN { p=0; c=0 }
    /^PUBLIC_APP_URL=/ { print "PUBLIC_APP_URL=" url; p=1; next }
    /^CORS_ORIGINS=/ { print "CORS_ORIGINS=" url; c=1; next }
    { print }
    END {
      if (!p) print "PUBLIC_APP_URL=" url
      if (!c) print "CORS_ORIGINS=" url
    }
  ' .env > "$tmp"
  mv "$tmp" .env
}

ensure_env_key() {
  local key="$1"
  local value="$2"
  [[ -f .env ]] || return 0
  if grep -qE "^${key}=" .env; then
    return 0
  fi
  printf '\n%s=%s\n' "$key" "$value" >> .env
}

ensure_slicer_env() {
  ensure_env_key SLICER_BIN prusa-slicer
  ensure_env_key STL_MAX_BYTES 83886080
  ensure_env_key SLICER_CPUS 2.0
  ensure_env_key SLICER_MEMORY 2g
}

ensure_docker

IP="$(detect_ip)"
if [[ -z "$HOST_URL" ]]; then
  HOST_URL="http://${IP}:3000"
fi

if [[ ! -f .env ]]; then
  say "Writing .env (secrets + public URL ${HOST_URL})"
  write_env "$HOST_URL"
else
  say "Keeping existing .env"
  if [[ "$HOST_SET" -eq 1 ]]; then
    set_host_in_env "$HOST_URL"
  else
    existing="$(grep -E '^PUBLIC_APP_URL=' .env | tail -n1 | cut -d= -f2- || true)"
    if [[ -n "$existing" ]]; then
      HOST_URL="$existing"
    fi
  fi
fi
ensure_slicer_env

say "Starting Print FarmOS (first run builds images, including PrusaSlicer, and can take several minutes)"
mkdir -p data/update
chmod 777 data/update 2>/dev/null || true
if [[ "$RESET" -eq 1 ]]; then
  say "Resetting farm data (docker compose down -v)"
  compose down -v --remove-orphans || true
fi
if [[ -d .git ]]; then
  APP_VERSION="$(git rev-parse --short HEAD 2>/dev/null || echo dev)"
  export APP_VERSION
  if [[ -f .env ]] && ! grep -q '^APP_VERSION=' .env; then
    echo "APP_VERSION=${APP_VERSION}" >> .env
  fi
fi
compose up -d --build
if ! compose ps --status running --format '{{.Name}}' 2>/dev/null | grep -q slicer-worker; then
  say "Starting slicer-worker (downloads PrusaSlicer on first build)"
  compose up -d --build slicer-worker || echo "slicer-worker did not start. Pack/preview still work; Slice needs that container."
fi

say "Waiting for the API, then the UI"
ready=0
for _ in $(seq 1 90); do
  api_ok=0
  ui_ok=0
  curl -fsS "http://127.0.0.1:8000/health" >/dev/null 2>&1 && api_ok=1
  curl -fsS "http://127.0.0.1:3000/api/v1/setup/status" >/dev/null 2>&1 && ui_ok=1
  if [[ "$api_ok" -eq 1 && "$ui_ok" -eq 1 ]]; then
    ready=1
    break
  fi
  sleep 2
done

echo
if [[ "$ready" -eq 1 ]]; then
  echo "Print FarmOS is running."
else
  echo "Containers are starting, but the UI is not answering yet."
  echo "Recent backend logs:"
  compose logs backend --tail 80 || true
  if compose logs backend 2>/dev/null | grep -q "password authentication failed"; then
    echo
    echo "The Postgres volume still has a password from an earlier install."
    echo "Wipe it and start clean (this deletes farm data) with:"
    echo "  ./install.sh --reset"
  fi
  echo
  echo "Check live logs with: docker compose logs -f"
fi
echo
echo "  Open:  ${HOST_URL}"
echo "  Local: http://127.0.0.1:3000"
echo
echo "First visit opens the setup wizard at ${HOST_URL}/setup — create an admin account."
echo "Uncheck Load demo data if this is a live shop."
echo "Slicer:  ${HOST_URL}/slicer  (slicer-worker uses PrusaSlicer; packing still works if Slice is waiting on first start)"
echo "If the wizard does not appear (leftover database), run: ./install.sh --reset"
echo
echo "Stop:    docker compose down"
echo "Update:  Settings → Update Print FarmOS, or ./update.sh"
echo "Backup:  ./scripts/backup.sh"
echo

say "Enabling one-click updates from Settings"
chmod +x scripts/update-agent.sh scripts/ensure-update-agent.sh update.sh
./scripts/ensure-update-agent.sh || true
