# Print FarmOS — one-command install for Windows + Docker Desktop.
# Usage:
#   .\install.ps1
#   .\install.ps1 -HostUrl http://192.168.1.50:3000
param(
  [string]$HostUrl = "",
  [switch]$Reset
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

if (-not (Test-Path ".\docker-compose.yml")) {
  Write-Error "Run this from the Print FarmOS folder (docker-compose.yml is missing)."
}

function Get-LanIp {
  $cfg = Get-NetIPConfiguration | Where-Object {
    $_.IPv4DefaultGateway -ne $null -and $_.NetAdapter.Status -eq "Up"
  } | Select-Object -First 1
  if ($cfg -and $cfg.IPv4Address) {
    return $cfg.IPv4Address.IPAddress
  }
  $addr = Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.IPAddress -notlike "127.*" -and $_.PrefixOrigin -ne "WellKnown" } |
    Select-Object -First 1
  if ($addr) { return $addr.IPAddress }
  return "127.0.0.1"
}

function New-Secret([int]$bytes = 36) {
  $raw = New-Object byte[] $bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($raw)
  return [Convert]::ToBase64String($raw).TrimEnd("=")
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Write-Error "Docker is not installed. Install Docker Desktop, start it, then re-run .\install.ps1"
}

docker info | Out-Null
if ($LASTEXITCODE -ne 0) {
  Write-Error "Docker is installed but not running. Start Docker Desktop, then re-run .\install.ps1"
}

$hostSet = $PSBoundParameters.ContainsKey("HostUrl") -and $HostUrl
if (-not $HostUrl) {
  $HostUrl = "http://$(Get-LanIp):3000"
}

if (-not (Test-Path ".\.env")) {
  Write-Host "==> Writing .env (secrets + public URL $HostUrl)"
  $secret = New-Secret 48
  $dbpass = (New-Secret 18) -replace "[^A-Za-z0-9]", ""
  @"
# Generated by install.ps1 — edit if you add WooCommerce, Shopify, or notifications.

SECRET_KEY=$secret
POSTGRES_PASSWORD=$dbpass
DATABASE_URL=postgresql+asyncpg://farmos:${dbpass}@db:5432/farmos
REDIS_URL=redis://redis:6379/0

CORS_ORIGINS=$HostUrl
PUBLIC_APP_URL=$HostUrl
SIMULATED_TIME_SCALE=1

WOOCOMMERCE_URL=
WOOCOMMERCE_KEY=
WOOCOMMERCE_SECRET=

SHOPIFY_SHOP=
SHOPIFY_ACCESS_TOKEN=
SHOPIFY_WEBHOOK_SECRET=
SHOPIFY_API_VERSION=2024-10

NTFY_SERVER=https://ntfy.sh
NTFY_TOPIC=
NTFY_TOKEN=

UPLOAD_DIR=/data
RUN_SCHEDULER=false
"@ | Set-Content -Path ".\.env" -Encoding ascii
} else {
  Write-Host "==> Keeping existing .env"
  if ($hostSet) {
    $text = Get-Content ".\.env" -Raw
    if ($text -match "(?m)^PUBLIC_APP_URL=") {
      $text = [regex]::Replace($text, "(?m)^PUBLIC_APP_URL=.*$", "PUBLIC_APP_URL=$HostUrl")
    } else {
      $text += "`nPUBLIC_APP_URL=$HostUrl`n"
    }
    if ($text -match "(?m)^CORS_ORIGINS=") {
      $text = [regex]::Replace($text, "(?m)^CORS_ORIGINS=.*$", "CORS_ORIGINS=$HostUrl")
    } else {
      $text += "`nCORS_ORIGINS=$HostUrl`n"
    }
    Set-Content -Path ".\.env" -Value $text -Encoding ascii -NoNewline
  } else {
    $existing = (Select-String -Path ".\.env" -Pattern "^PUBLIC_APP_URL=" | Select-Object -Last 1)
    if ($existing) {
      $HostUrl = $existing.Line.Substring("PUBLIC_APP_URL=".Length)
    }
  }
}

Write-Host "==> Starting Print FarmOS (first run builds images and can take several minutes)"
New-Item -ItemType Directory -Force -Path (Join-Path $PSScriptRoot "data\update") | Out-Null
if ($Reset) {
  Write-Host "==> Resetting farm data (docker compose down -v)"
  docker compose down -v --remove-orphans
}
docker compose up -d --build
if ($LASTEXITCODE -ne 0) {
  Write-Error "docker compose failed"
}

Write-Host ""
Write-Host "Print FarmOS is starting."
Write-Host "  Open:  $HostUrl"
Write-Host "  Local: http://127.0.0.1:3000"
Write-Host ""
Write-Host "First visit opens the setup wizard at $HostUrl/setup — create an admin account."
Write-Host "Uncheck Load demo data if this is a live shop."
Write-Host "If the wizard does not appear (leftover database), run: .\install.ps1 -Reset"
Write-Host ""
Write-Host "Stop:    docker compose down"
Write-Host "Update:  Settings → Update Print FarmOS, or .\update.ps1"
Write-Host "Backup:  bash ./scripts/backup.sh"

$agentDir = Join-Path $PSScriptRoot "data\update"
New-Item -ItemType Directory -Force -Path $agentDir | Out-Null
$pidFile = Join-Path $agentDir "agent.pid"
$running = $false
if (Test-Path $pidFile) {
  $oldId = Get-Content $pidFile | Select-Object -First 1
  if ($oldId -and (Get-Process -Id $oldId -ErrorAction SilentlyContinue)) { $running = $true }
}
if (-not $running) {
  $proc = Start-Process -FilePath "powershell.exe" -ArgumentList @(
    "-NoProfile", "-WindowStyle", "Hidden", "-File", (Join-Path $PSScriptRoot "scripts\update-agent.ps1")
  ) -PassThru
  $proc.Id | Set-Content $pidFile
  Write-Host "Update agent started. Settings → Update Print FarmOS is now available."
}
