#!/usr/bin/env python3
"""Stand-in PrusaSlicer CLI for unit tests. Writes G-code with Prusa footer comments."""

from __future__ import annotations

import argparse
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--load")
    parser.add_argument("--export-gcode", action="store_true")
    parser.add_argument("--output")
    parser.add_argument("stl", nargs="*")
    args, _unknown = parser.parse_known_args()
    out = Path(args.output or "plate.gcode")
    if out.suffix.lower() != ".gcode":
        out = out / "plate.gcode"
    out.parent.mkdir(parents=True, exist_ok=True)
    copies = 1
    stl_path = Path(args.stl[0]) if args.stl else None
    if stl_path and stl_path.is_file():
        copies = max(1, stl_path.stat().st_size // 400 or 1)
        copies = min(copies, 40)
    seconds = 4200 * copies
    grams = 12.89 * copies
    cm3 = 10.40 * copies
    mm = 4321.09 * copies
    out.write_text(
        f"""; generated by PrusaSlicer 2.9.2 (FarmOS test mock)
; filament_diameter = 1.75
; filament_density = 1.27
; filament_type = PETG
; layer_height = 0.20
; nozzle_diameter = 0.4
; estimated printing time (normal mode) = {seconds // 3600}h {(seconds % 3600) // 60}m {seconds % 60}s
; filament used [mm] = {mm:.2f}
; filament used [cm3] = {cm3:.2f}
; filament used [g] = {grams:.2f}
; total filament used [g] = {grams:.2f}
G28
G1 X10 Y10 F3000
M84
""",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
