import unittest

from app.services.gcode_meta import apply_filename_time_fallback, parse_gcode_comments
from app.util import parse_time_from_filename


class FilenameTimeTests(unittest.TestCase):
    def test_compact_hours_minutes(self):
        self.assertEqual(parse_time_from_filename("Handle-2h15m.gcode"), 2 * 3600 + 15 * 60)

    def test_underscore_before_token(self):
        self.assertEqual(parse_time_from_filename("RK-FR5-Handle_1h12m.gcode"), 1 * 3600 + 12 * 60)

    def test_spaces_between_parts(self):
        self.assertEqual(parse_time_from_filename("Part 2h 15m.gcode"), 2 * 3600 + 15 * 60)

    def test_hour_and_min_words(self):
        self.assertEqual(parse_time_from_filename("Part-2hr15min.gcode"), 2 * 3600 + 15 * 60)

    def test_hours_minutes_seconds(self):
        self.assertEqual(parse_time_from_filename("Handle-1h12m08s.gcode"), 1 * 3600 + 12 * 60 + 8)

    def test_minutes_only(self):
        self.assertEqual(parse_time_from_filename("clip-45m.gcode"), 45 * 60)

    def test_minutes_word(self):
        self.assertEqual(parse_time_from_filename("rack-90min.gcode"), 90 * 60)

    def test_decimal_hours(self):
        self.assertEqual(parse_time_from_filename("Handle-1.5h.gcode"), int(1.5 * 3600))

    def test_implied_minutes_after_hours(self):
        self.assertEqual(parse_time_from_filename("Handle-1h30.gcode"), 1 * 3600 + 30 * 60)

    def test_clock_hms(self):
        self.assertEqual(parse_time_from_filename("Part-2:15:00.gcode"), 2 * 3600 + 15 * 60)

    def test_clock_hm(self):
        self.assertEqual(parse_time_from_filename("Part-1:12.gcode"), 1 * 3600 + 12 * 60)

    def test_underscore_between_parts(self):
        self.assertEqual(parse_time_from_filename("Handle_2h_15m.gcode"), 2 * 3600 + 15 * 60)

    def test_parentheses(self):
        self.assertEqual(parse_time_from_filename("Handle_(2h15m).gcode"), 2 * 3600 + 15 * 60)
        self.assertEqual(parse_time_from_filename("Handle-(2h15m)-PETG.gcode"), 2 * 3600 + 15 * 60)

    def test_uses_last_duration(self):
        self.assertEqual(parse_time_from_filename("2h-final-45m.gcode"), 45 * 60)

    def test_ignores_quantity_x4(self):
        self.assertIsNone(parse_time_from_filename("RK-FR5-Handle-x4.gcode"))

    def test_ignores_nozzle_0_4(self):
        self.assertIsNone(parse_time_from_filename("Handle-0.4.gcode"))
        self.assertIsNone(parse_time_from_filename("Handle-0.4mm.gcode"))

    def test_ignores_printer_model_suffix(self):
        self.assertIsNone(parse_time_from_filename("K1Max2.gcode"))

    def test_ignores_unbounded_digits(self):
        self.assertIsNone(parse_time_from_filename("Handle2h15m.gcode"))

    def test_ignores_version_v2(self):
        self.assertIsNone(parse_time_from_filename("Handle-v2.gcode"))

    def test_empty_and_plain_names(self):
        self.assertIsNone(parse_time_from_filename("RK-FR5-Handle.gcode"))
        self.assertIsNone(parse_time_from_filename(""))


class FilenameTimeFallbackTests(unittest.TestCase):
    def test_filename_fills_when_comments_missing(self):
        meta: dict = {}
        self.assertTrue(apply_filename_time_fallback(meta, "Test-2h15m.gcode"))
        self.assertEqual(meta["estimated_time_seconds"], 2 * 3600 + 15 * 60)

    def test_comments_win_over_filename(self):
        meta = parse_gcode_comments(
            "; generated by PrusaSlicer 2.7.4\n"
            "; estimated printing time (normal mode) = 1h 12m 8s\n"
        )
        self.assertFalse(apply_filename_time_fallback(meta, "Handle-2h15m.gcode"))
        self.assertEqual(meta["estimated_time_seconds"], 1 * 3600 + 12 * 60 + 8)

    def test_does_not_invent_time(self):
        meta: dict = {}
        self.assertFalse(apply_filename_time_fallback(meta, "Handle-x4.gcode"))
        self.assertNotIn("estimated_time_seconds", meta)


if __name__ == "__main__":
    unittest.main()
