import unittest

from app.services.gcode_meta import (
    apply_filename_filament_fallback,
    apply_filename_time_fallback,
    parse_gcode_comments,
)
from app.util import (
    parse_filament_grams_from_filename,
    parse_quantity_from_filename,
    parse_time_from_filename,
)


class FilenameGramsTests(unittest.TestCase):
    def test_dash_before_token(self):
        self.assertEqual(parse_filament_grams_from_filename("Handle-48g.gcode"), 48)

    def test_underscore_before_token(self):
        self.assertEqual(parse_filament_grams_from_filename("RK-FR5-Handle_48g.gcode"), 48)

    def test_decimal_grams(self):
        self.assertEqual(parse_filament_grams_from_filename("Handle-48.5g.gcode"), 48.5)

    def test_spaces_between_number_and_unit(self):
        self.assertEqual(parse_filament_grams_from_filename("Part 48 g.gcode"), 48)

    def test_grams_word(self):
        self.assertEqual(parse_filament_grams_from_filename("Handle-48grams.gcode"), 48)

    def test_gram_singular(self):
        self.assertEqual(parse_filament_grams_from_filename("Handle-48gram.gcode"), 48)

    def test_gr_abbreviation(self):
        self.assertEqual(parse_filament_grams_from_filename("Handle-48gr.gcode"), 48)

    def test_parentheses(self):
        self.assertEqual(parse_filament_grams_from_filename("Handle_(48g).gcode"), 48)
        self.assertEqual(parse_filament_grams_from_filename("Handle-(48g)-PETG.gcode"), 48)

    def test_combined_with_time(self):
        self.assertEqual(parse_filament_grams_from_filename("Handle_2h15m_48g.gcode"), 48)

    def test_combined_with_qty_and_time(self):
        name = "RK-FR5-Handle-x4-2h15m-48g.gcode"
        self.assertEqual(parse_filament_grams_from_filename(name), 48)
        self.assertEqual(parse_time_from_filename(name), 2 * 3600 + 15 * 60)
        self.assertEqual(parse_quantity_from_filename(name), 4)

    def test_uses_last_grams(self):
        self.assertEqual(parse_filament_grams_from_filename("12g-final-48g.gcode"), 48)

    def test_ignores_quantity_x4(self):
        self.assertIsNone(parse_filament_grams_from_filename("RK-FR5-Handle-x4.gcode"))

    def test_ignores_nozzle_0_4(self):
        self.assertIsNone(parse_filament_grams_from_filename("Handle-0.4.gcode"))
        self.assertIsNone(parse_filament_grams_from_filename("Handle-0.4mm.gcode"))

    def test_ignores_printer_model_suffix(self):
        self.assertIsNone(parse_filament_grams_from_filename("K1Max2.gcode"))

    def test_ignores_meters_without_g(self):
        self.assertIsNone(parse_filament_grams_from_filename("Handle-12.3m.gcode"))

    def test_ignores_time_only(self):
        self.assertIsNone(parse_filament_grams_from_filename("Handle-2h15m.gcode"))

    def test_ignores_unbounded_digits(self):
        self.assertIsNone(parse_filament_grams_from_filename("Handle48g.gcode"))

    def test_ignores_green(self):
        self.assertIsNone(parse_filament_grams_from_filename("Handle-48green.gcode"))

    def test_ignores_out_of_range(self):
        self.assertIsNone(parse_filament_grams_from_filename("Handle-0g.gcode"))
        self.assertIsNone(parse_filament_grams_from_filename("Handle-100001g.gcode"))

    def test_empty_and_plain_names(self):
        self.assertIsNone(parse_filament_grams_from_filename("RK-FR5-Handle.gcode"))
        self.assertIsNone(parse_filament_grams_from_filename(""))


class FilenameGramsFallbackTests(unittest.TestCase):
    def test_filename_fills_when_comments_missing(self):
        meta: dict = {}
        self.assertTrue(apply_filename_filament_fallback(meta, "Test-48g.gcode"))
        self.assertEqual(meta["estimated_filament_grams"], 48)

    def test_comments_win_over_filename(self):
        meta = parse_gcode_comments(
            "; generated by PrusaSlicer 2.7.4\n"
            "; filament used [g] = 12.89\n"
            "; total filament used [g] = 12.89\n"
        )
        self.assertFalse(apply_filename_filament_fallback(meta, "Handle-99g.gcode"))
        self.assertEqual(meta["estimated_filament_grams"], 12.89)

    def test_does_not_invent_grams(self):
        meta: dict = {}
        self.assertFalse(apply_filename_filament_fallback(meta, "Handle-x4.gcode"))
        self.assertNotIn("estimated_filament_grams", meta)

    def test_independent_of_time_fallback(self):
        meta = parse_gcode_comments(
            "; generated by PrusaSlicer 2.7.4\n"
            "; estimated printing time (normal mode) = 1h 12m 8s\n"
        )
        self.assertIn("estimated_time_seconds", meta)
        self.assertNotIn("estimated_filament_grams", meta)
        self.assertFalse(apply_filename_time_fallback(meta, "Handle-2h15m-48g.gcode"))
        self.assertTrue(apply_filename_filament_fallback(meta, "Handle-2h15m-48g.gcode"))
        self.assertEqual(meta["estimated_time_seconds"], 1 * 3600 + 12 * 60 + 8)
        self.assertEqual(meta["estimated_filament_grams"], 48)


if __name__ == "__main__":
    unittest.main()
