import unittest

from app.services.gcode_meta import gcode_text_for_metadata, parse_gcode_comments, parse_gcode_metadata


CURA = """
;FLAVOR:Marlin
;TIME:4521
;Filament used: 3.20m, 0.10m
;Layer height: 0.2
;TIME_ELAPSED:12
; generated by Cura_SteamEngine 5.7
"""

PRUSA = """
; generated by PrusaSlicer 2.7.4 on 2026-01-02
; filament_diameter = 1.75
; filament_density = 1.27
; filament_type = PETG
; layer_height = 0.28
; nozzle_diameter = 0.4
; estimated first layer printing time (normal mode) = 2m 10s
; estimated printing time (silent mode) = 1h 40m 0s
; estimated printing time (normal mode) = 1h 12m 8s
; filament used [mm] = 4321.09
; filament used [cm3] = 10.40
; filament used [g] = 12.89
; total filament used [g] = 12.89
"""

ORCA = """
; generated by OrcaSlicer 2.2.0
; model printing time: 51m 20s; total estimated time: 55m 2s
; total filament weight [g] : 16.23
; filament used [g] = 12.00, 4.23
"""

IDEAMAKER = """
;Print Time: 2 hours 15 minutes 30 seconds
;Filament used: 4.5m
; filament_type = PLA
"""


class GcodeMetadataTests(unittest.TestCase):
    def test_cura_header(self):
        meta = parse_gcode_comments(CURA)
        self.assertEqual(meta["estimated_time_seconds"], 4521)
        self.assertGreater(meta["estimated_filament_grams"], 8)
        self.assertEqual(meta["layer_height_mm"], 0.2)

    def test_ignores_time_elapsed(self):
        meta = parse_gcode_metadata(";TIME_ELAPSED:99\n;TIME:40\n")
        self.assertEqual(meta["estimated_time_seconds"], 40)

    def test_prusa_footer_prefers_grams_and_normal_time(self):
        meta = parse_gcode_comments(PRUSA)
        self.assertEqual(meta["estimated_time_seconds"], 1 * 3600 + 12 * 60 + 8)
        self.assertEqual(meta["estimated_filament_grams"], 12.89)
        self.assertEqual(meta["nozzle_mm"], 0.4)
        self.assertIn("PrusaSlicer", str(meta.get("slicer")))

    def test_skips_first_layer_time(self):
        meta = parse_gcode_comments(
            "; estimated first layer printing time (normal mode) = 2m 10s\n"
            "; estimated printing time (normal mode) = 10m 0s\n"
        )
        self.assertEqual(meta["estimated_time_seconds"], 600)

    def test_orca_total_time_and_multi_tool_grams(self):
        meta = parse_gcode_comments(ORCA)
        self.assertEqual(meta["estimated_time_seconds"], 55 * 60 + 2)
        self.assertEqual(meta["estimated_filament_grams"], 16.23)

    def test_ideamaker_hours_minutes(self):
        meta = parse_gcode_comments(IDEAMAKER)
        self.assertEqual(meta["estimated_time_seconds"], 2 * 3600 + 15 * 60 + 30)

    def test_length_to_grams_uses_diameter_and_density(self):
        meta = parse_gcode_comments(
            "; filament_diameter = 1.75\n"
            "; filament_density = 1.24\n"
            "; filament used [mm] = 1000\n"
        )
        self.assertAlmostEqual(float(meta["estimated_filament_grams"]), 2.99, delta=0.05)

    def test_reads_footer_past_thumbnail_blob(self):
        blob = CURA + ("x" * 900_000) + PRUSA
        raw = blob.encode("utf-8")
        text = gcode_text_for_metadata(raw)
        meta = parse_gcode_comments(text)
        self.assertEqual(meta["estimated_time_seconds"], 1 * 3600 + 12 * 60 + 8)
        self.assertEqual(meta["estimated_filament_grams"], 12.89)

    def test_m73_fallback(self):
        meta = parse_gcode_comments("G28\nM73 P0 R22\nG1 X0\n")
        self.assertEqual(meta["estimated_time_seconds"], 22 * 60)

    def test_compact_comment_duration(self):
        meta = parse_gcode_comments("; total estimated time: 2h15m\n")
        self.assertEqual(meta["estimated_time_seconds"], 2 * 3600 + 15 * 60)

    def test_empty(self):
        self.assertEqual(parse_gcode_metadata("G28\nG1 X10\n"), {})


if __name__ == "__main__":
    unittest.main()
