import unittest

from app.services.costing import filament_line_cost
from app.services.plate_pack import (
    clamp_spacing,
    copies_to_pack,
    max_quantity,
    pack_copies,
    plan_plates,
    spacing_hint,
    validate_plate,
)
from app.services.slicer_cli import slicer_argv
from app.services.slicer_compat import printer_slice_issues
from app.services.slicer_estimate import grams_from_slicer_meta
from app.services.slicer_filename import sliced_gcode_filename, sanitise_upload_name
from app.services.gcode_meta import parse_gcode_comments


class FilenameTests(unittest.TestCase):
    def test_readable_gcode_name(self) -> None:
        name = sliced_gcode_filename("RK-FR5-Handle", "Flex Rack 5 Handle", 12, "Bay-02 K1 Max", 3)
        self.assertEqual(name, "RK-FR5-Handle-x12-K1Max-v3.gcode")

    def test_sanitise_upload(self) -> None:
        self.assertEqual(sanitise_upload_name("../../evil name.STL"), "evil-name.stl")


class PackingTests(unittest.TestCase):
    def test_stays_in_printable_area(self) -> None:
        packed = pack_copies(50, 50, 220, 220, 9, 8)
        self.assertGreaterEqual(packed.quantity, 9)
        for part in packed.placed:
            self.assertGreaterEqual(part.x, -1e-6)
            self.assertGreaterEqual(part.y, -1e-6)
            self.assertLessEqual(part.x + part.w, 220.001)
            self.assertLessEqual(part.y + part.h, 220.001)
        self.assertFalse(validate_plate(packed))

    def test_rotation_can_beat_axis_aligned_grid(self) -> None:
        packed = pack_copies(80, 30, 220, 100, 20, 8)
        self.assertGreaterEqual(packed.quantity, 6)
        self.assertTrue(any(p.rotation_z in (90.0, 270.0) for p in packed.placed) or packed.quantity >= 6)

    def test_spacing_changes_max_qty(self) -> None:
        tight = max_quantity(20, 20, 100, 100, 2)
        wide = max_quantity(20, 20, 100, 100, 30)
        self.assertGreater(tight, wide)
        self.assertGreaterEqual(tight, 16)
        self.assertEqual(wide, 4)

    def test_slider_count_is_not_forced_to_fill(self) -> None:
        packed = pack_copies(20, 20, 100, 100, 3, 6)
        self.assertEqual(packed.quantity, 3)
        self.assertGreater(packed.max_quantity, 3)
        self.assertEqual(packed.spacing_mm, 6)

    def test_full_plate_sits_at_max_quantity(self) -> None:
        max_q = max_quantity(20, 20, 100, 100, 8)
        filled = pack_copies(20, 20, 100, 100, copies_to_pack(None, True, max_q), 8)
        self.assertGreater(max_q, 1)
        self.assertEqual(filled.quantity, max_q)
        self.assertEqual(filled.max_quantity, max_q)
        self.assertEqual(filled.spacing_mm, 8)

    def test_copies_to_pack_full_plate_is_max(self) -> None:
        self.assertEqual(copies_to_pack(None, False, 12), 12)
        self.assertEqual(copies_to_pack(4, True, 12), 12)
        self.assertEqual(copies_to_pack(4, False, 12), 4)
        self.assertEqual(copies_to_pack(1, False, 1), 1)

    def test_keepout_blocks_corner(self) -> None:
        packed = pack_copies(
            40,
            40,
            100,
            100,
            8,
            6,
            keepouts=[{"x": 0, "y": 0, "w": 50, "h": 50}],
        )
        for part in packed.placed:
            overlap_x = part.x < 50 and part.x + part.w > 0
            overlap_y = part.y < 50 and part.y + part.h > 0
            self.assertFalse(overlap_x and overlap_y)

    def test_even_plates_avoid_leftover_one(self) -> None:
        greedy = plan_plates(43, 14, "balanced")
        even = plan_plates(43, 14, "minimum_bed_clears")
        self.assertEqual(sum(greedy), 43)
        self.assertEqual(sum(even), 43)
        self.assertGreaterEqual(min(even), 10)

    def test_spacing_hint(self) -> None:
        self.assertEqual(spacing_hint(3, 6), "Tight")
        self.assertEqual(spacing_hint(6, 6), "Recommended")
        self.assertEqual(spacing_hint(14, 6), "Conservative")

    def test_clamp(self) -> None:
        self.assertEqual(clamp_spacing(1), 2)
        self.assertEqual(clamp_spacing(40), 30)


class CostAndMetaTests(unittest.TestCase):
    def test_grams_times_price(self) -> None:
        line = filament_line_cost(100, 0.024)
        self.assertTrue(line["costed"])
        self.assertAlmostEqual(line["filament_cost"], 2.4)

    def test_selected_density_not_generic_plastic(self) -> None:
        comments = (
            "; generated by PrusaSlicer 2.7.4\n"
            "; filament used [cm3] = 10.00\n"
            "; filament used [mm] = 4000\n"
            "; estimated printing time (normal mode) = 1h 0m 0s\n"
        )
        meta = parse_gcode_comments(comments)
        pla = grams_from_slicer_meta(meta, 1.24)
        petg = grams_from_slicer_meta(meta, 1.27)
        self.assertIsNotNone(pla[0])
        self.assertIsNotNone(petg[0])
        self.assertNotAlmostEqual(pla[0], petg[0])
        self.assertAlmostEqual(petg[0], 12.7, places=1)


class GeometryTests(unittest.TestCase):
    def test_usable_prefers_model_over_marketing(self) -> None:
        from types import SimpleNamespace

        from app.services.printer_geometry import apply_printer_geometry_defaults

        printer = SimpleNamespace(
            name="Bay-02 K1 Max",
            model="Creality K1 Max",
            build_x_mm=None,
            build_y_mm=None,
            build_z_mm=None,
            usable_x_mm=None,
            usable_y_mm=None,
            usable_z_mm=None,
            nozzle_diameter_mm=None,
            firmware="",
        )
        apply_printer_geometry_defaults(printer)
        self.assertEqual(printer.build_x_mm, 300)
        self.assertEqual(printer.usable_x_mm, 290)
        self.assertEqual(printer.firmware, "klipper")


class CompatibilityTests(unittest.TestCase):
    def test_nozzle_mismatch_reason(self) -> None:
        class P:
            name = "K1 Max"
            is_enabled = True
            current_downtime_reason = None
            status = type("S", (), {"value": "idle", "__eq__": lambda self, o: True})()
            usable_x_mm = 290
            usable_y_mm = 290
            usable_z_mm = 250
            build_x_mm = 300
            build_y_mm = 300
            build_z_mm = 250
            nozzle_diameter_mm = 0.4
            supported_materials = ["PETG"]
            max_nozzle_temp_c = 300
            max_bed_temp_c = 100
            firmware = "klipper"
            model = "K1 Max"
            keepout_polygons = []
            bed_origin = "corner"
            bed_shape = "rectangular"
            filament_diameter_mm = 1.75

        class Profile:
            nozzle_mm = 0.6
            material = "PETG"
            compatible_printer_ids = []
            nozzle_temp_c = 250
            bed_temp_c = 80
            name = "PETG 0.6"

        from app.models import PrinterStatus

        printer = P()
        printer.status = PrinterStatus.idle
        issues = printer_slice_issues(printer, profile=Profile())  # type: ignore[arg-type]
        self.assertTrue(any("0.6" in i and "0.4" in i for i in issues))


class QueuePayloadTests(unittest.TestCase):
    def test_argv_never_joins_user_strings(self) -> None:
        from pathlib import Path

        argv = slicer_argv(
            "/usr/bin/prusa-slicer",
            Path("/tmp/a.ini"),
            Path("/tmp/evil name;rm.stl"),
            Path("/tmp/out.gcode"),
        )
        self.assertIsInstance(argv, list)
        self.assertEqual(argv[0], "/usr/bin/prusa-slicer")
        self.assertIn("/tmp/evil name;rm.stl", argv)
        joined = " ".join(argv)
        self.assertNotIn("rm.stl &&", joined)

    def test_job_fields_for_queue(self) -> None:
        payload = {
            "gcode_file_id": "g1",
            "assigned_printer_id": "p1",
            "part_id": "part1",
            "quantity_produced": 12,
            "estimated_time_seconds": 4200,
            "estimated_filament_grams": 48.2,
            "slice_job_id": "s1",
            "production_run_id": "run1",
            "material": "PETG",
        }
        self.assertEqual(payload["quantity_produced"], 12)
        self.assertIn("slice_job_id", payload)
        self.assertEqual(payload["estimated_time_seconds"], 4200)


class MockSlicerTests(unittest.TestCase):
    def test_mock_cli_gcode_parses(self) -> None:
        import subprocess
        import tempfile
        from pathlib import Path

        from app.services.gcode_meta import parse_gcode_file

        script = Path(__file__).resolve().parents[1] / "scripts" / "mock_prusa_slicer.py"
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "plate.gcode"
            stl = Path(tmp) / "part.stl"
            stl.write_bytes(b"x" * 500)
            completed = subprocess.run(
                ["python3", str(script), "--load", str(Path(tmp) / "x.ini"), "--export-gcode", "--output", str(out), "--", str(stl)],
                check=True,
                capture_output=True,
            )
            self.assertEqual(completed.returncode, 0)
            meta = parse_gcode_file(out)
            self.assertGreater(meta["estimated_time_seconds"], 60)
            self.assertGreater(meta["estimated_filament_grams"], 1)
            self.assertIn("filament_volume_cm3", meta)


if __name__ == "__main__":
    unittest.main()
