"""Build a PrusaSlicer INI from the printer record + versioned profile.

FarmOS never accepts arbitrary CLI flags from the browser. Only these known
keys are written.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.models import Printer, SlicerProfile
from app.services.printer_geometry import bed_origin, bed_shape, usable_bed

_GCODE_FLAVOR = {
    "klipper": "klipper",
    "marlin": "marlin",
    "marlin2": "marlin2",
    "reprap": "reprap",
    "smoothie": "smoothie",
}


def _flavor(printer: Printer) -> str:
    fw = (printer.firmware or "").strip().lower()
    if fw in _GCODE_FLAVOR:
        return _GCODE_FLAVOR[fw]
    model = f"{printer.model} {printer.name}".lower()
    if any(k in model for k in ("k1", "k2", "voron", "klipper")):
        return "klipper"
    return "marlin"


def _bed_shape_ini(printer: Printer) -> str:
    w, d, _z = usable_bed(printer)
    if bed_shape(printer) == "circular":
        r = min(w, d) / 2.0
        return f"0x{r:.3f},{r:.3f}x0"
    if bed_origin(printer) == "center":
        hx, hy = w / 2.0, d / 2.0
        return f"{-hx:.3f}x{-hy:.3f},{hx:.3f}x{-hy:.3f},{hx:.3f}x{hy:.3f},{-hx:.3f}x{hy:.3f}"
    return f"0x0,{w:.3f}x0,{w:.3f}x{d:.3f},0x{d:.3f}"


def profile_to_ini_dict(printer: Printer, profile: SlicerProfile) -> dict[str, str]:
    extra = dict(profile.settings_json or {})
    nozzle = float(profile.nozzle_mm or printer.nozzle_diameter_mm or 0.4)
    diameter = float(printer.filament_diameter_mm or 1.75)
    density = float(profile.density_g_cm3 or 1.27)
    layer = float(profile.layer_height_mm or 0.2)
    first = float(profile.first_layer_height_mm or layer)
    infill = float(profile.infill_percent or 20)
    speed = float(profile.print_speed_mm_s or 80)
    data: dict[str, str] = {
        "printer_technology": "FFF",
        "gcode_flavor": _flavor(printer),
        "bed_shape": _bed_shape_ini(printer),
        "nozzle_diameter": f"{nozzle:g}",
        "filament_diameter": f"{diameter:g}",
        "filament_density": f"{density:g}",
        "filament_type": (profile.material or "PETG").upper(),
        "layer_height": f"{layer:g}",
        "first_layer_height": f"{first:g}",
        "perimeters": str(int(profile.perimeters or 3)),
        "fill_density": f"{infill:g}%",
        "temperature": f"{float(profile.nozzle_temp_c or 250):g}",
        "first_layer_temperature": f"{float(profile.nozzle_temp_c or 250):g}",
        "bed_temperature": f"{float(profile.bed_temp_c or 80):g}",
        "first_layer_bed_temperature": f"{float(profile.bed_temp_c or 80):g}",
        "brim_width": f"{float(profile.brim_width_mm or 0):g}",
        "support_material": "1" if profile.support_enabled else "0",
        "perimeter_speed": f"{speed:g}",
        "infill_speed": f"{speed:g}",
        "travel_speed": f"{min(speed * 2.5, float(printer.max_speed_mm_s or 300)):g}",
        "max_print_speed": f"{float(printer.max_speed_mm_s or max(speed * 2, 120)):g}",
    }
    if printer.max_volumetric_mm3_s:
        data["max_volumetric_speed"] = f"{float(printer.max_volumetric_mm3_s):g}"
    if printer.max_accel_mm_s2:
        data["machine_max_acceleration_x"] = f"{float(printer.max_accel_mm_s2):g}"
        data["machine_max_acceleration_y"] = f"{float(printer.max_accel_mm_s2):g}"
    allowed_extra = {
        "fill_pattern",
        "solid_infill_speed",
        "first_layer_speed",
        "support_material_style",
        "skirts",
        "skirt_distance",
        "retract_length",
        "retract_speed",
        "layer_gcode",
        "start_gcode",
        "end_gcode",
        "before_layer_gcode",
        "use_relative_e_distances",
        "only_one_perimeter_top",
    }
    for key, value in extra.items():
        if key in allowed_extra and value is not None:
            data[str(key)] = str(value)
    return data


def write_ini(path: Path, values: dict[str, str]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by Print FarmOS — do not edit by hand while a slice is running"]
    for key in sorted(values):
        lines.append(f"{key} = {values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def build_ini_file(path: Path, printer: Printer, profile: SlicerProfile) -> Path:
    return write_ini(path, profile_to_ini_dict(printer, profile))
